apiVersion: v2
name: app
description: A Helm chart for the  Spring Boot application
version: 0.1.0
dependencies:
  - name: mysql
    version: "12.2.2"
    repository: "https://charts.bitnami.com/bitnami"
