mysql:
  enabled: true
  imageTag: "8.4.4-debian-12-r0"  
  database: "challenge"  
  service:
    port: 3306

  auth:
    rootPassword: ""

app:
  image:
    repository: ma957/challenge
    tag: latest
  service:
    type: LoadBalancer
    port: 8080
  env:
    SPRING_DATASOURCE_PASSWORD: "" 
    SPRING_DATASOURCE_URL: "jdbc:mysql://app-mysql:3306/challenge?createDatabaseIfNotExist=true"
    SPRING_DATASOURCE_WRITER_URL: "jdbc:mysql://app-mysql:3306/challenge?createDatabaseIfNotExist=true"

