apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: {{ .Values.namespace | default "app" }}  # Use namespace from values.yaml or default to "app"
spec:
  type: {{ .Values.app.service.type }}
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: 8080
  selector:
    app: app
